//@ sourceMappingURL=client.map
// Generated by CoffeeScript 1.6.1

/*
  Здесь реализован весь клиентский JavaScript. Подразумевается, что модель
  подключается заранее.
*/


(function() {

  (function($) {
    return $(document).ready(function() {
      var ChangeWord, FindDistanceX, FindDistanceY, Location, Wc, me, setBDiv, setPlayerDiv, socket;
      socket = io.connect(document.URL.match(/^http:\/\/[^/]*/));
      /*
      Viewer=(obj)->
        if (obj instanceof Player)
          html = """
                <div id='#{@name}' class='player'>
                  <div class='left' style='background:rgb(#{50},#{255},#{20});display: inline-block;width: 10px;'>#{@ml}</div>
                  <div class="main" style='background:rgb(#{255},#{0},#{0});display: inline-block;width: 70px;'>#{@name}</div>
                  <div class='right' style='background:rgb(#{50},#{255},#{20});display: inline-block;width:20px;'>#{@mr}</div>
                </div>
                """
          return html
        if (obj instanceof Enemy)
          return alert "This is class Enemy"
      */

      ChangeWord = function() {
        var w;
        w = "" + (String.fromCharCode(Math.ceil(65 + Math.random() * 25)));
        while (w === me.ml || w === me.mr || w === me.mu || w === me.md) {
          w = "" + (String.fromCharCode(Math.ceil(65 + Math.random() * 25)));
        }
        return w;
      };
      FindDistanceX = function(p1, p2) {
        var d, dx, x1, x2, y1, y2;
        x1 = p1.x + $('#' + p1.name).outerWidth() / 2;
        y1 = p1.y + $('#' + p1.name).outerHeight() / 2;
        x2 = p2.x + $('#' + p2.name).outerWidth() / 2;
        y2 = p2.y - $('#' + p2.name).outerHeight() / 2;
        d = Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
        dx = Math.acos((x2 - x1) / d) * 10;
        console.log("dx=" + dx);
        return dx;
      };
      FindDistanceY = function(p1, p2) {
        var d, dy, x1, x2, y1, y2;
        x1 = p1.x + $('#' + p1.name).outerWidth() / 2;
        y1 = p1.y + $('#' + p1.name).outerHeight() / 2;
        x2 = p2.x + $('#' + p2.name).outerWidth() / 2;
        y2 = p2.y - $('#' + p2.name).outerHeight() / 2;
        d = Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
        dy = Math.asin((y2 - y1) / d) * 10;
        console.log("dy=" + dy);
        return dy;
      };
      Location = function(p1, p2) {
        if (p1.x < p2.x && p1.y > p2.y) {
          return 1;
        }
        if (p1.x < p2.x && p1.y < p2.y) {
          return 4;
        }
        if (p1.x > p2.x && p1.y < p2.y) {
          return 3;
        }
        if (p1.x > p2.x && p1.y > p2.y) {
          return 2;
        }
      };
      setPlayerDiv = function(pl) {
        var p;
        p = $('#' + pl.name);
        if (p.length === 0) {
          p = $(document.body).append(pl.html(0));
          p = $('#' + pl.name);
        } else {
          p = p.html(pl.html(1));
        }
        p.css('left', pl.x + 'px');
        return p.css('top', pl.y + 'px');
      };
      setBDiv = function(B) {
        var b;
        b = $('#' + B.name);
        if (b.length === 0) {
          b = $(document.body).append(B.html());
          b = $('#' + B.name);
        } else {
          b = b.html(B.html());
        }
        b.css('left', B.x + 'px');
        return b.css('top', B.y + 'px');
      };
      Wc = new World();
      console.log("Wc.name=" + Wc.name);
      me = new Player();
      socket.emit('add user', me);
      socket.on('change name', function(number) {
        me.number = number;
        return me.name = me.number;
      });
      socket.on('Shut Up And Take My World', function(Ws) {
        var pl, _i, _len, _ref;
        Wc = new World(Ws);
        _ref = Wc.Players;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pl = _ref[_i];
          setPlayerDiv(new Player(pl));
        }
        return console.log("Wc.name=" + Wc.name);
      });
      socket.on('user have been added', function(pl) {
        setPlayerDiv(new Player(pl));
        Wc.AddPlayer(pl);
        return console.log("Joined " + Wc.Players[pl.number].name);
      });
      socket.on('user have been changed', function(pl) {
        setPlayerDiv(new Player(pl));
        return Wc.ChangePlayer(pl);
      });
      socket.on('bullet have been added', function(pl) {
        Wc.ChangePlayer(pl);
        setBDiv(new Bullet(pl.Bullets[pl.countB - 1]));
        return console.log('bullet have been added');
      });
      socket.on('bullet have been changed', function(B) {
        setBDiv(new Bullet(B));
        Wc.ChangeBullet(B);
        return console.log("bullet have been changed");
      });
      return $("body").keydown(function(e) {
        var B, D, dx, dy, r, _ref;
        if (e.keyCode === 32) {
          B = new Bullet(me);
          console.log(B.name, B.number);
          me.AddBullet(B);
          socket.emit('add bullet', me);
          setBDiv(B);
          r = Location(me, Wc.Players[1]);
          console.log("r=" + r);
          dx = FindDistanceX(me, Wc.Players[1]);
          console.log("cdx" + dx);
          dy = FindDistanceY(me, Wc.Players[1]);
          console.log("cdy" + dy);
          D = setInterval(function() {
            B.Replace(dx, dy, r);
            me.ChangeBullet(B);
            socket.emit('add bullet', me);
            return setBDiv(B);
          }, 1000);
        }
        if (String.fromCharCode(e.keyCode) === me.ml) {
          me.MoveTo(1);
          me.ml = ChangeWord();
          console.log(me.ml);
        }
        if (String.fromCharCode(e.keyCode) === me.mr) {
          me.MoveTo(3);
          me.mr = ChangeWord();
          console.log("mr=" + me.mr);
        }
        if (String.fromCharCode(e.keyCode) === me.mu) {
          me.MoveTo(2);
          me.mu = ChangeWord();
          console.log(me.mu);
        }
        if (String.fromCharCode(e.keyCode) === me.md) {
          me.MoveTo(4);
          me.md = ChangeWord();
          console.log(me.md);
        }
        if ((65 <= (_ref = e.keyCode) && _ref <= 90)) {
          Wc.ChangePlayer(me);
          setPlayerDiv(me);
          return socket.emit('change user', me);
        }
      });
    });
  })(jQuery);

}).call(this);
